title: Polyphenol Estimator
description: A tutorial on how to obtain estimates of polyphenol intake and DII from diet recall or record data.
theme: just-the-docs
markdown: kramdown

url: https://swi1.github.io/polyphenol_estimator/

aux_links:
  GitHub Repository: https://github.com/SWi1/polyphenol_estimator